# Generated by Django 4.0.3 on 2022-03-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('seasson', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventsHasGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celero.event')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celero.game')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteHasEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('noc', models.CharField(max_length=3)),
                ('team', models.CharField(max_length=25)),
                ('medal', models.CharField(max_length=6)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('atlheteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celero.athlete')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celero.event')),
            ],
        ),
    ]
