# Generated by Django 4.0.3 on 2022-03-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
