# Generated by Django 4.0.3 on 2022-03-31 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athletehasevents',
            old_name='atlheteId_id',
            new_name='atlhete',
        ),
        migrations.RenameField(
            model_name='athletehasevents',
            old_name='eventId_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventshasgame',
            old_name='eventId_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventshasgame',
            old_name='gameId_id',
            new_name='game',
        ),
    ]
