# Generated by Django 4.0.3 on 2022-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celero', '0003_rename_atlhete_athletehasevents_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletehasevents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
