# Generated by Django 4.0.3 on 2022-03-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celero', '0004_alter_athletehasevents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletehasevents',
            name='medal',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
